### ISSUE TITLE
JIT reorder kernel for SVE 256 and SVE 128

### ISSUE THREAD

**Issue by cfRod** [fujitsu/oneDNN#59]
Hi, 

I have some questions regarding the JIT - reorder AArch64 kernel  in the main oneDNN repository that I am investigating for SVE 256 and SVE 128 . 
For SVE 256, I was able run the JIT reorder kernel with a small change to enable it (mayiuse(sve_256)) on the a64fx and I was able to run the reorder tests from benchdnn with tests:24533 passed:14617 skipped:9916 which is the same as SVE 512. I also observed performance benefits over the simple reorder kernel. 

However, with SVE-128, I have noted some benchdnn failures with looks to be related to when input type != output type and for some blocked data formats (attached logs)
[benchdnn-failed-128.log](https://github.com/fujitsu/oneDNN/files/6391196/benchdnn-failed-128.log). I got tests:24533 passed:3830 skipped:9916 mistrusted:0 unimplemented:0 failed:10787. Are these known non-supported cases for SVE 128?

**Comment by kawakami-k** [comment]
Hi, @cfRod 
Thank you for the investigation and comments. I'll check your log. Please wait a week, since this week and next week are major holidays in Japan. Sorry for inconvenience.  The latest branch is fj_rls-v2.1, so it would be nice if you could evaluate fj_rls-v2.1.

BTW, how do you use the A64FX as SVE 256 and 128? Did you use the following command for SVE 256?
```
echo 32 > /proc/sys/abi/sve_default_vector_length
```

Thanks.

**Comment by cfRod** [comment]
Hi @kawakami-k,

Thanks for your response. I tested this on master in oneDNN's repository (https://github.com/oneapi-src/oneDNN).  I was also testing v2.2 branch. I made two changes: I used a script that can set "prctl(PR_SVE_SET_VL, vl") to a particular vector length and I made a change here using (mayiuse(x)) : https://github.com/oneapi-src/oneDNN/blob/ca6ca816faa92025a231f3ff1d110b73c5a460c1/src/cpu/aarch64/jit_uni_reorder.cpp#L124 (to test SVE 256 and 128). I can try the fj_rls-v2.1 branch next week.

**Comment by kawakami-k** [comment]
Hi @cfRod 

`process_unroll_tr8x8` requires more than or equal to 256 bits as the SVE register width, because it transposes an 8x8 matrix of 32-bit data on the SVE registers. In other cases, it seems that the condition can be relaxed to 128 bits. I'll make a patch and send a pull request to Intel in a few days!

Thanks.

**Comment by kawakami-k** [comment]
Hi @cfRod 

I made the patch for ASIMD/SVE128/SVE256 jit reorder.
Please try
https://github.com/kawakami-k/oneDNN/tree/reorder_sve_4

I also sent this patch as the PR to Intel
https://github.com/oneapi-src/oneDNN/pull/1050

Thanks.

**Comment by cfRod** [comment]
Hi @kawakami-k ,

Thanks, I will take a look.

**Comment by cfRod** [comment]
Hi, I've tested this patch using benchdnn for SVE512, 256 and 128. It looks okay to me. Thanks.
```
tests:24533 passed:7529 skipped:17004 mistrusted:0 unimplemented:0 failed:0 listed:0
```
